// Generated by tools/build-developer-lockup.py. Do not edit by hand.
//
// Regenerate after changing anything in content/brand/:
//   python tools/build-developer-lockup.py

export const DEVELOPER_PARTIES = ["Shoal Group", "969 Development Company Limited", "Gabonn Associates"] as const;

export const DEVELOPER_ALT = "Shoal Group, 969 Development Company Limited and Gabonn Associates";
