/**
 * Approved content for the Explorer Towers public site.
 *
 * Source imagery: `content/` in the project root, copied to `public/media/`
 * by `tools/sync-assets.py`. Every still supplied so far is an architectural
 * render, so `kind` is "render" throughout — no item claims to be site
 * photography until real photographs are handed over.
 *
 * Fields flagged `pending()` are the §14 "open inputs before launch" list.
 * They render as an approved alternative, never as a plausible guess.
 */
import developersArtwork from "../../public/media/brand/developers.png";

import { DEVELOPER_ALT, DEVELOPER_PARTIES } from "./developer-lockup.generated";

import {
  approved,
  pending,
  type Amenity,
  type AnimationScene,
  type Download,
  type Film,
  type InteriorRoom,
  type FaqSection,
  type Media,
  type ProgressUpdate,
  type ProjectFact,
  type VideoClip,
  type Publishable,
  type ResidenceType,
} from "./types";

const EXT = { width: 1834, height: 1024 } as const;
const EXT_TRIMMED = { width: 1379, height: 1024 } as const;
/** Delivery variants are all normalised to 1080p by `tools/encode-video.py`. */
const WALK = { width: 1920, height: 1080 } as const;
const INT = { width: 1672, height: 941 } as const;

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/**
 * Spec "Basis and scope": the source filename says Shoal Group, the proposal
 * cover says Gabonn Associates. Explorer Towers is the working project title
 * until the legal entity and public developer name are confirmed.
 */
export const identity = {
  projectName: "Explorer Towers",
  /** Text form of the mark, for accessible names and page titles. */
  wordmark: "EXPLORER",
  /**
   * Confirmed by the client. This resolves the question the specification
   * raised in "Basis and scope": the source filename said Shoal Group while
   * the proposal cover said Gabonn Associates. Neither was the answer — the
   * developer is 969 Development Company Limited, and Shoal Group appears
   * alongside it as the second party on the approved lockup.
   */
  developer: approved("969 Development Company Limited") as Publishable<string>,
  tagline: "Curved-balcony residences above Kampala",
  /*
   * Confirmed by the client. Not yet the canonical URL: SITE_URL still
   * points at the Vercel address until DNS for this domain resolves, so
   * canonicals and the sitemap cannot advertise a host nobody can reach.
   */
  domain: approved("www.explorertower.ug") as Publishable<string>,
};

/**
 * The approved developer lockup.
 *
 * The two marks were supplied as one piece of artwork and are used as one:
 * `tools/build-developer-lockup.py` only trims the white ground, so the pairing,
 * spacing and proportions are exactly as delivered. Never separate them, put
 * anything between them, or reorder them.
 *
 * The Shoal block is dark with reversed type, so on a dark background the
 * lockup sits on a light plate rather than being recoloured.
 */
/**
 * Width and height come from the file itself through Next's static image
 * import, not from numbers typed here. The lockup is generated by
 * `tools/build-developer-lockup.py` and changes shape whenever a party is
 * added, so hard-coded dimensions would silently distort the marks the next
 * time it is rebuilt.
 */
export const developerLockup = {
  src: developersArtwork.src,
  width: developersArtwork.width,
  height: developersArtwork.height,
  alt: DEVELOPER_ALT,
  /** In the order the artwork sets them. */
  parties: DEVELOPER_PARTIES,
} as const;

export const contact = {
  address: approved(
    "Plot 35 John Babiha (Acacia) Avenue, Kampala, Uganda",
  ) as Publishable<string>,
  phone: approved("+256 750 421224") as Publishable<string>,
  whatsapp: approved("+256 750 421224") as Publishable<string>,
  email: approved("brightthoughtsservices@gmail.com") as Publishable<string>,
  hours: approved("9:30am to 7:00pm") as Publishable<string>,
  /**
   * Confirmed by the client from a dropped Google Maps pin. Kampala sits just
   * north of the equator, so the latitude is a small positive number — that is
   * correct, not a truncated value.
   */
  coordinates: approved({
    lat: 0.3281903,
    lng: 32.5870894,
  }) as Publishable<{ lat: number; lng: number }>,
};

/** Digits only, for `tel:` and `wa.me` links. */
export const contactDigits = {
  phone: "256750421224",
  whatsapp: "256750421224",
} as const;

/**
 * Marketing and lead generation are run by Bright Properties, credited on the
 * site as the marketing agent — distinct from the developer, who is credited
 * with the approved lockup.
 */
export const marketingAgent = {
  /** The brand on the supplied logo. */
  name: "Bright Properties",
  /**
   * The entity behind the brand, as it appears on the proposal, the Google
   * Maps listing and the contact address. Both names are shown where the
   * office is given, so a visitor looking for the office finds the right sign.
   */
  legalName: "Bright Thoughts Services",
  role: "Marketing by",
  logo: "/media/brand/bright-properties.png",
  office: {
    address: "8JC3+CPM, Third St, Kampala",
    coordinates: { lat: 0.3210625, lng: 32.6043125 },
    mapsUrl: "https://maps.app.goo.gl/xsXVLDhs34NdPCdX7",
  },
} as const;

// ---------------------------------------------------------------------------
// Media library
// ---------------------------------------------------------------------------

export const media = {
  streetDay: {
    src: "/media/exterior/street-day.webp",
    width: 2400,
    height: 1350,
    alt: "Explorer Towers from the street in daylight, its curved balconies planted along every edge above a colonnade of travertine columns.",
    caption: "From John Babiha (Acacia) Avenue",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  facadeLookingUp: {
    src: "/media/exterior/facade-looking-up.webp",
    width: 2400,
    height: 1350,
    alt: "Looking up the facade of Explorer Towers, the curved balcony edges stacking away against the sky with planting spilling over each one.",
    caption: "The curve, from below",
    kind: "render",
    category: "exterior",
    focal: "50% 50%",
  },
  facadeDusk: {
    src: "/media/exterior/facade-dusk.webp",
    width: 2400,
    height: 1350,
    alt: "Explorer Towers at dusk, every balcony lit from beneath and the interiors glowing through full-height glazing.",
    caption: "The facade at dusk",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  aerialNight: {
    src: "/media/exterior/aerial-night.webp",
    width: 2400,
    height: 1350,
    alt: "Explorer Towers lit at night, seen from the air above Kololo with the lights of Kampala spread out behind it.",
    caption: "Above Kololo, at night",
    kind: "render",
    category: "exterior",
    focal: "50% 50%",
  },
  aerialDusk: {
    src: "/media/exterior/aerial-dusk.webp",
    width: 2400,
    height: 1350,
    alt: "An aerial view at dusk of Explorer Towers standing above the surrounding streets and rooftops of Kampala.",
    caption: "Aerial, dusk",
    kind: "render",
    category: "exterior",
    focal: "50% 50%",
  },
  poolTerraceDay: {
    src: "/media/exterior/pool-terrace-day.webp",
    width: 1672,
    height: 941,
    alt: "The first-floor pool terrace in daylight, the pool running along the building edge beneath the curved balconies above.",
    caption: "Pool terrace, first floor",
    kind: "render",
    category: "amenities",
  },
  poolAndGym: {
    src: "/media/exterior/pool-and-gym.webp",
    width: 1672,
    height: 941,
    alt: "The first-floor pool with the glazed gym alongside it, and the glass canopy over the parking below.",
    caption: "Pool and gym, first floor",
    kind: "render",
    category: "amenities",
  },
  poolFromGarden: {
    src: "/media/exterior/pool-from-garden.webp",
    width: 1672,
    height: 941,
    alt: "The pool and wellness level seen from the garden, with the ivory travertine facade rising behind.",
    caption: "Wellness level from the garden",
    kind: "render",
    category: "amenities",
  },
  gatedEntrance: {
    src: "/media/exterior/gated-entrance.webp",
    width: 1920,
    height: 1080,
    alt: "The gated vehicle entrance to Explorer Towers, with the Explorer mark set into the brass screen.",
    caption: "The gated entrance",
    kind: "render",
    category: "exterior",
  },
  streetGoldenHour: {
    src: "/media/exterior/street-golden-hour.png",
    ...EXT,
    alt: "Explorer Towers seen from the street at golden hour, its stacked curved balconies wrapping the corner of the tower.",
    caption: "Street approach, golden hour",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  frontElevationDusk: {
    src: "/media/exterior/front-elevation-dusk.png",
    ...EXT,
    alt: "Front elevation of Explorer Towers at dusk, with planted balcony edges and warm interior light across every floor.",
    caption: "Front elevation, dusk",
    kind: "render",
    category: "exterior",
    focal: "50% 42%",
  },
  cornerEvening: {
    src: "/media/exterior/corner-evening.png",
    ...EXT,
    alt: "Corner view of Explorer Towers after sunset, balcony edges picked out in continuous lines of light.",
    caption: "Corner view, evening",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  cornerDaylight: {
    src: "/media/exterior/corner-daylight.png",
    ...EXT,
    alt: "Explorer Towers in daylight, showing the full height of the curved balcony stack and the cantilevered roof blade.",
    caption: "Corner view, daylight",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  sectionCutawayDusk: {
    src: "/media/exterior/section-cutaway-dusk.png",
    ...EXT,
    alt: "Cutaway section of Explorer Towers at dusk, showing lit apartments floor by floor around the suspended penthouse pool.",
    caption: "Sectional study, dusk",
    kind: "render",
    category: "exterior",
    focal: "50% 45%",
  },
  arrivalPodium: {
    src: "/media/exterior/arrival-podium.png",
    ...EXT_TRIMMED,
    alt: "The arrival level beneath Explorer Towers, with a covered drop-off, a glazed fitness room above and parking beyond.",
    caption: "Arrival and podium level",
    kind: "render",
    category: "exterior",
    focal: "50% 50%",
  },
  skyPoolTerrace: {
    src: "/media/amenities/sky-pool-terrace.png",
    ...INT,
    alt: "A swimmer rests at the infinity edge of the penthouse pool at dusk, looking out over the lights of Kampala.",
    caption: "The penthouse pool, dusk",
    kind: "render",
    category: "amenities",
    focal: "45% 50%",
  },
  penthousePool: {
    src: "/media/amenities/sky-pool-penthouse.webp",
    width: 1614,
    height: 975,
    alt: "A penthouse pool suspended in the facade at sunset, its glass edge looking out over the city, with the residence behind it.",
    caption: "Penthouse pool, suspended in the facade",
    kind: "render",
    category: "amenities",
  },
  lobbyLounge: {
    src: "/media/amenities/lobby-lounge.webp",
    width: 1672,
    height: 941,
    alt: "The ground-floor lobby lounge at golden hour, a curved sofa beneath a brass ring light, glazed on two sides to the garden.",
    caption: "Lobby lounge",
    kind: "render",
    category: "amenities",
  },
  reception: {
    src: "/media/amenities/reception.webp",
    width: 1672,
    height: 941,
    alt: "The reception desk in ivory travertine, with the sunken lounge beyond it.",
    caption: "Reception",
    kind: "render",
    category: "amenities",
  },
  mediaRoom: {
    src: "/media/amenities/media-room.webp",
    width: 1672,
    height: 941,
    alt: "A media room with a long walnut table, wall-mounted display and slatted timber walls, glazed to the garden.",
    caption: "Media room",
    kind: "render",
    category: "amenities",
  },
  conferenceRoom: {
    src: "/media/amenities/conference-room.webp",
    width: 1672,
    height: 941,
    alt: "The conference room, seating fourteen at a walnut table with a wall display and full-height glazing alongside.",
    caption: "Conference room",
    kind: "render",
    category: "amenities",
  },
  residentsLounge: {
    src: "/media/amenities/residents-lounge.webp",
    width: 1672,
    height: 941,
    alt: "The residents' lounge, armchairs gathered on a rug with the dining hall and bar beyond.",
    caption: "Residents' lounge",
    kind: "render",
    category: "amenities",
  },
  meetingRoom: {
    src: "/media/amenities/meeting-room.webp",
    width: 1672,
    height: 941,
    alt: "A meeting room with a long walnut table under brass pendants, travertine columns down one side.",
    caption: "Meeting room",
    kind: "render",
    category: "amenities",
  },
  diningHall: {
    src: "/media/amenities/dining-hall.webp",
    width: 1672,
    height: 941,
    alt: "The dining hall, a long walnut table beneath a line of brass globe pendants, lit from the glazing at the far end.",
    caption: "Dining hall",
    kind: "render",
    category: "amenities",
  },
  sauna: {
    src: "/media/amenities/sauna.webp",
    width: 1800,
    height: 1012,
    alt: "The sauna, lined and benched in pale travertine.",
    caption: "Sauna",
    kind: "render",
    category: "amenities",
  },
  playground: {
    src: "/media/amenities/playground.webp",
    width: 1800,
    height: 1012,
    alt: "The children's play area in the garden, shaded and fenced, with the building's columns rising behind it.",
    caption: "Children's play area",
    kind: "render",
    category: "amenities",
  },
  gateDetail: {
    src: "/media/amenities/gate-detail.webp",
    width: 1920,
    height: 1080,
    alt: "Close-up of the vehicle gate, the Explorer goat-and-hill mark cut into a brass screen of vertical slats, with the travertine building behind.",
    caption: "The gate, with the Explorer mark",
    kind: "render",
    category: "amenities",
  },
  steamRoom: {
    src: "/media/amenities/steam-room.webp",
    width: 1800,
    height: 1012,
    alt: "The steam room, tiled floor to ceiling in blue mosaic, with two tiered benches along the walls.",
    caption: "Steam room",
    kind: "render",
    category: "amenities",
  },
  yogaStudio: {
    src: "/media/amenities/yoga-studio.webp",
    width: 1920,
    height: 1080,
    alt: "The yoga and floor exercise studio, a timber-floored room with rows of black mats laid out and full-height glazing along one side.",
    caption: "Yoga and floor exercise studio",
    kind: "render",
    category: "amenities",
  },
  skyPoolFacade: {
    src: "/media/amenities/sky-pool-facade.png",
    ...INT,
    alt: "The penthouse pool seen from outside the building, cantilevered between floors with residences visible above and below.",
    caption: "The penthouse pool, suspended in the facade",
    kind: "render",
    category: "amenities",
    focal: "50% 50%",
  },
} as const satisfies Record<string, Media>;

const threeBed = {
  entranceHall: {
    src: "/media/residences/3-bed/entrance-hall.png",
    ...INT,
    alt: "Three-bedroom entrance hall looking through to the living and dining rooms, with a console table and a stone feature wall.",
    caption: "Three-bedroom · entrance hall",
    kind: "render",
    category: "interior",
  },
  living: {
    src: "/media/residences/3-bed/living.png",
    ...INT,
    alt: "Three-bedroom living room with a curved sectional sofa, brass ring chandelier and floor-to-ceiling curved glazing over the city.",
    caption: "Three-bedroom · living room",
    kind: "render",
    category: "interior",
    focal: "55% 50%",
  },
  dining: {
    src: "/media/residences/3-bed/dining.png",
    ...INT,
    alt: "Three-bedroom dining area seating ten at a stone table, opening into the living room and the balcony beyond.",
    caption: "Three-bedroom · dining",
    kind: "render",
    category: "interior",
  },
  kitchen: {
    src: "/media/residences/3-bed/kitchen.png",
    ...INT,
    alt: "Three-bedroom kitchen with a veined stone island, breakfast seating, walnut joinery and integrated ovens.",
    caption: "Three-bedroom · kitchen",
    kind: "render",
    category: "interior",
  },
  principalBedroom: {
    src: "/media/residences/3-bed/principal-bedroom.png",
    ...INT,
    alt: "Three-bedroom principal suite with an upholstered headboard wall, curved corner glazing and a lit walk-in dressing room.",
    caption: "Three-bedroom · principal suite",
    kind: "render",
    category: "interior",
  },
  principalBathroom: {
    src: "/media/residences/3-bed/principal-bathroom.png",
    ...INT,
    alt: "Three-bedroom principal bathroom with a freestanding stone bath by the window, a walk-in rain shower and a twin vanity.",
    caption: "Three-bedroom · principal bathroom",
    kind: "render",
    category: "interior",
  },
  guestBedroom: {
    src: "/media/residences/3-bed/guest-bedroom.png",
    ...INT,
    alt: "Three-bedroom guest suite with fitted walnut wardrobes, a writing desk, balcony access and an en-suite shower room.",
    caption: "Three-bedroom · guest suite",
    kind: "render",
    category: "interior",
  },
} as const satisfies Record<string, Media>;

const twoBed = {
  living: {
    src: "/media/residences/2-bed/living.png",
    ...INT,
    alt: "Two-bedroom living room with a curved sofa facing the balcony, kitchen and dining beyond in one open plan.",
    caption: "Two-bedroom · living room",
    kind: "render",
    category: "interior",
    focal: "50% 50%",
  },
  dining: {
    src: "/media/residences/2-bed/dining.png",
    ...INT,
    alt: "Two-bedroom dining area with an oval stone table for eight, framed artwork and the living room behind.",
    caption: "Two-bedroom · dining",
    kind: "render",
    category: "interior",
  },
  kitchen: {
    src: "/media/residences/2-bed/kitchen.png",
    ...INT,
    alt: "Two-bedroom open kitchen with a long stone island and breakfast stools, looking through to the balcony.",
    caption: "Two-bedroom · kitchen",
    kind: "render",
    category: "interior",
  },
  principalBedroom: {
    src: "/media/residences/2-bed/principal-bedroom.png",
    ...INT,
    alt: "Two-bedroom principal suite with curved corner glazing onto a furnished balcony and an en-suite bathroom alongside.",
    caption: "Two-bedroom · principal suite",
    kind: "render",
    category: "interior",
  },
  principalBathroom: {
    src: "/media/residences/2-bed/principal-bathroom.png",
    ...INT,
    alt: "Two-bedroom principal bathroom with a freestanding bath, a walk-in rain shower and a twin stone vanity.",
    caption: "Two-bedroom · principal bathroom",
    kind: "render",
    category: "interior",
  },
  secondBedroom: {
    src: "/media/residences/2-bed/second-bedroom.png",
    ...INT,
    alt: "Two-bedroom second bedroom with fitted wardrobes, a dressing table and an en-suite shower room.",
    caption: "Two-bedroom · second bedroom",
    kind: "render",
    category: "interior",
  },
} as const satisfies Record<string, Media>;

// ---------------------------------------------------------------------------
// Opening sequence (spec §3)
// ---------------------------------------------------------------------------

/**
 * Five scenes across one pinned sequence. The first is painted immediately as
 * the poster; the rest crossfade on scroll. Stills only — a continuous
 * exterior-to-interior camera move needs matching approved footage, and spec
 * §3 forbids fabricating one from unrelated stills.
 */
export const animationScenes: readonly AnimationScene[] = [
  {
    id: "arrival",
    media: media.streetGoldenHour,
    mobileFocal: "50% 38%",
    kicker: "Acacia Avenue, Kampala",
    heading: "Explorer Towers",
    body: "Curved-balcony residences with the city on every horizon.",
    zoomTo: 1.06,
  },
  {
    id: "street",
    media: media.streetDay,
    mobileFocal: "50% 42%",
    kicker: "John Babiha (Acacia) Avenue",
    heading: "On the avenue",
    body: "Travertine columns carry the building over a colonnade at street level.",
    zoomTo: 1.04,
  },
  {
    id: "elevation",
    media: media.facadeLookingUp,
    mobileFocal: "50% 45%",
    kicker: "The facade",
    heading: "One curve, carried the full height",
    body: "Every balcony edge is drawn as a single unbroken line, planted along its length.",
    zoomTo: 1.05,
  },
  {
    id: "wellness",
    media: media.poolAndGym,
    mobileFocal: "50% 50%",
    kicker: "The first floor",
    heading: "A pool, and a gym beside it",
    body: "A whole floor given to wellness and work — pool, gym, sauna, steam room, studio and meeting rooms.",
    zoomTo: 1.05,
  },
  {
    id: "interior",
    media: threeBed.living,
    mobileFocal: "55% 50%",
    kicker: "Inside",
    heading: "Rooms that follow the curve",
    body: "Living spaces open along the full sweep of the glazing.",
    zoomTo: 1.04,
  },
];

// ---------------------------------------------------------------------------
// Residences
// ---------------------------------------------------------------------------

export const residences: readonly ResidenceType[] = [
  {
    slug: "two-bedroom",
    name: "Two-bedroom residence",
    shortName: "Two bedroom",
    bedrooms: 2,
    area: pending("Request the schedule of areas"),
    areaBasis: pending("Area basis to be confirmed"),
    price: approved("From USD 300,000"),
    priceFrom: { amount: 300000, currency: "USD" },
    metaDescription:
      "Two-bedroom apartments for sale in Kololo, Kampala, from USD 300,000. Open living, two en-suite bedrooms and a private balcony.",
    availability: pending("Request current availability"),
    paymentPlan: pending("Request payment terms"),
    floorPlan: pending("Floor plan available on request"),
    summary:
      "Open living, dining and kitchen along the curved glazing, with two en-suite bedrooms and a balcony off the principal suite.",
    features: [
      "Open-plan living, dining and kitchen",
      "Curved floor-to-ceiling glazing to the living space",
      "Stone island kitchen with integrated appliances",
      "Two bedrooms, both en-suite",
      "Fitted walnut wardrobes and dressing table to the second bedroom",
      "Principal bathroom with freestanding bath and walk-in shower",
      "Private balcony",
    ],
    hero: twoBed.living,
    gallery: [
      twoBed.living,
      twoBed.dining,
      twoBed.kitchen,
      twoBed.principalBedroom,
      twoBed.principalBathroom,
      twoBed.secondBedroom,
    ],
  },
  {
    slug: "three-bedroom",
    name: "Three-bedroom residence",
    shortName: "Three bedroom",
    bedrooms: 3,
    area: pending("Request the schedule of areas"),
    areaBasis: pending("Area basis to be confirmed"),
    price: approved("From USD 400,000"),
    priceFrom: { amount: 400000, currency: "USD" },
    metaDescription:
      "Three-bedroom apartments for sale in Kololo, Kampala, from USD 400,000. Private entrance hall, principal suite with dressing room, balcony.",
    availability: pending("Request current availability"),
    paymentPlan: pending("Request payment terms"),
    floorPlan: pending("Floor plan available on request"),
    summary:
      "A private entrance hall opening to separate living and dining rooms along the curve, with a principal suite, dressing room and further en-suite bedrooms.",
    features: [
      "Private entrance hall",
      "Separate living and dining rooms along the curved glazing",
      "Stone island kitchen with breakfast seating and integrated ovens",
      "Principal suite with walk-in dressing room",
      "Principal bathroom with freestanding bath and twin vanity",
      "Further en-suite bedrooms with fitted joinery",
      "Balcony access from the principal rooms",
    ],
    hero: threeBed.living,
    gallery: [
      threeBed.entranceHall,
      threeBed.living,
      threeBed.dining,
      threeBed.kitchen,
      threeBed.principalBedroom,
      threeBed.principalBathroom,
      threeBed.guestBedroom,
    ],
  },
  {
    slug: "penthouse",
    name: "Six-bedroom duplex penthouses",
    shortName: "Penthouses",
    bedrooms: 6,
    area: pending("Request the penthouse area schedule"),
    areaBasis: pending("Area basis to be confirmed"),
    price: pending("Price on application — talk to us"),
    metaDescription:
      "Luxury six-bedroom duplex penthouses for sale in Kololo, Kampala, each with a private suspended pool and cinema room. Price on application.",
    availability: pending("Request current availability"),
    paymentPlan: pending("Request payment terms"),
    floorPlan: pending("Penthouse plan available on request"),
    summary:
      "Two duplex penthouses crown the building, a mirrored pair across the tenth and eleventh floors. Each has six bedrooms over two levels, its own swimming pool and pool deck suspended in the facade, a private cinema room and a sunken lounge — all belonging to that residence alone.",
    /**
     * The pool and cinema are confirmed by the client. Everything else here is
     * what the approved renders actually show — the room-by-room schedule
     * follows once penthouse drawings are handed over.
     */
    features: [
      "Two penthouses only, a mirrored pair over the tenth and eleventh floors",
      "Six bedrooms arranged across two levels",
      "Private swimming pool and pool deck, suspended in the facade",
      "Private cinema room",
      "Sunken lounge beside the pool deck",
      "Principal suite with walk-in dressing room and study",
      "Private lounge on the upper level",
      "Staff quarters, pantry and laundry to each residence",
      "Terraces on both levels",
    ],
    hero: media.skyPoolTerrace,
    gallery: [media.skyPoolTerrace, media.skyPoolFacade, media.sectionCutawayDusk],
    /**
     * Spec §2: no invented interiors. The penthouse is shown through the
     * approved pool and sectional renders until its own set is supplied — and
     * the cinema room has no render at all, so it is described, not pictured.
     */
    mediaNote:
      "Penthouse interiors have not yet been released. These images show the suspended pool and the sectional study. The dimensioned plans for both penthouse levels are in the floor plan set on the Downloads page.",
  },
];

// ---------------------------------------------------------------------------
// Walkthrough clips (three-bedroom)
// ---------------------------------------------------------------------------

/**
 * Five-second walkthroughs of the three-bedroom residence. Each is paired with
 * a poster taken from the clip itself (`tools/make-posters.py`), so the still a
 * visitor sees before pressing play is the frame the video opens on.
 */
const clip = (
  index: number,
  alt: string,
  caption: string,
): VideoClip => ({
  src: `/media/residences/3-bed/walkthrough-${index}.mp4`,
  durationLabel: "5s",
  poster: {
    src: `/media/residences/3-bed/walkthrough-${index}.jpg`,
    ...WALK,
    alt,
    caption,
    kind: "render",
    category: "interior",
  },
});

const walkthroughs = {
  dining: clip(
    1,
    "Walkthrough of the three-bedroom dining room, panning past the round table towards the living room.",
    "Three-bedroom · dining walkthrough",
  ),
  balcony: clip(
    2,
    "Walkthrough of the three-bedroom balcony, moving along the outdoor dining setting with the city beyond the glass balustrade.",
    "Three-bedroom · balcony walkthrough",
  ),
  entrance: clip(
    3,
    "Walkthrough of the three-bedroom entrance hall, moving past the console and artwork towards the living rooms.",
    "Three-bedroom · entrance walkthrough",
  ),
  living: clip(
    4,
    "Walkthrough of the three-bedroom living room, sweeping across the curved sofa to the full-height glazing.",
    "Three-bedroom · living walkthrough",
  ),
  kitchen: clip(
    5,
    "Walkthrough of the three-bedroom kitchen, tracking along the stone island and breakfast seating.",
    "Three-bedroom · kitchen walkthrough",
  ),
} as const;

// ---------------------------------------------------------------------------
// Exterior films
// ---------------------------------------------------------------------------

/**
 * Five-second exterior clips supplied as 4K masters and delivered here as
 * 1080p variants with posters cut from the clips themselves
 * (`tools/encode-video.py`). Nothing plays until a visitor asks it to.
 */
const film = (
  index: number,
  id: string,
  title: string,
  alt: string,
): Film => ({
  id,
  title,
  clip: {
    src: `/media/exterior/film-${index}.mp4`,
    durationLabel: "5s",
    poster: {
      src: `/media/exterior/film-${index}.jpg`,
      ...WALK,
      alt,
      caption: title,
      kind: "render",
      category: "exterior",
    },
  },
});

export const films: readonly Film[] = [
  film(3, "street", "Street approach",
    "Looking up at Explorer Towers from the pavement at golden hour, the balcony stack rising above the trees."),
  film(6, "sunset", "The tower at sunset",
    "The full height of Explorer Towers seen across the road as the sun sets behind it."),
  film(2, "arrival", "Driving in",
    "Arriving by car, turning off the road and passing under the podium of Explorer Towers."),
  film(4, "podium", "Under the podium",
    "The covered arrival level, with residents crossing to the lobby and cars parked beneath the building."),
  film(5, "forecourt", "The forecourt at dusk",
    "The lit forecourt and drop-off beneath Explorer Towers after dark."),
  film(7, "facade", "Down the facade",
    "An aerial pass down the face of Explorer Towers, showing the penthouse pool suspended at the centre."),
  film(1, "pool", "The penthouse pool",
    "The infinity edge of the penthouse pool at dusk, with the lights of Kampala beyond."),
];

// ---------------------------------------------------------------------------
// Interior showcase
// ---------------------------------------------------------------------------

/**
 * The interiors, read room by room rather than residence by residence, so a
 * visitor can compare the same room across residence types. Copy describes only
 * what is visible in the approved renders.
 */
export const interiorRooms: readonly InteriorRoom[] = [
  {
    id: "living",
    name: "Living room",
    tagline: "Along the curve",
    body: "The sofa follows the sweep of the glazing rather than facing away from it, so the room is oriented to the view on every seat. Stone and walnut run the length of the media wall, lit from within.",
    views: [
      { label: "Three bedroom", media: threeBed.living, clip: walkthroughs.living },
      { label: "Two bedroom", media: twoBed.living },
    ],
  },
  {
    id: "dining",
    name: "Dining",
    tagline: "Open to the room",
    body: "A single stone table under sculptural brass pendants, set in the same volume as the living room so the two read as one space with the balcony beyond.",
    views: [
      { label: "Three bedroom", media: threeBed.dining, clip: walkthroughs.dining },
      { label: "Two bedroom", media: twoBed.dining },
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    tagline: "Stone and walnut",
    body: "A full-height island in veined stone with breakfast seating, integrated ovens behind walnut joinery, and a lit backsplash carried across the run.",
    views: [
      { label: "Three bedroom", media: threeBed.kitchen, clip: walkthroughs.kitchen },
      { label: "Two bedroom", media: twoBed.kitchen },
    ],
  },
  {
    id: "principal-bedroom",
    name: "Principal suite",
    tagline: "Turned to the view",
    body: "The bed faces an upholstered headboard wall while the corner glazing curves away to the balcony. In the three-bedroom the dressing room opens directly off the suite.",
    views: [
      { label: "Three bedroom", media: threeBed.principalBedroom },
      { label: "Two bedroom", media: twoBed.principalBedroom },
    ],
  },
  {
    id: "principal-bathroom",
    name: "Principal bathroom",
    tagline: "Light on stone",
    body: "A freestanding bath set at the window, a walk-in rain shower behind glass, and a twin vanity beneath a backlit mirror.",
    views: [
      { label: "Three bedroom", media: threeBed.principalBathroom },
      { label: "Two bedroom", media: twoBed.principalBathroom },
    ],
  },
  {
    id: "second-bedroom",
    name: "Second bedroom",
    tagline: "Fully fitted",
    body: "Wall-to-wall walnut wardrobes, a dressing table at the window and an en-suite shower room — specified as a principal room in its own right.",
    views: [
      { label: "Three bedroom", media: threeBed.guestBedroom },
      { label: "Two bedroom", media: twoBed.secondBedroom },
    ],
  },
  {
    id: "balcony",
    name: "Balcony",
    tagline: "Outside the glazing",
    body: "The balcony runs the width of the principal rooms behind a frameless glass balustrade, wide enough to dine on, with the city on the far side.",
    views: [
      {
        label: "Three bedroom",
        media: walkthroughs.balcony.poster,
        clip: walkthroughs.balcony,
      },
    ],
  },
  {
    id: "entrance",
    name: "Entrance hall",
    tagline: "The arrival inside",
    body: "The three-bedroom opens through a private hall, with a stone feature wall and a console before the living rooms come into view.",
    views: [
      { label: "Three bedroom", media: threeBed.entranceHall, clip: walkthroughs.entrance },
    ],
  },
];

// ---------------------------------------------------------------------------
// Amenities — only what is legible in the approved renders (spec §2)
// ---------------------------------------------------------------------------

export const amenities: readonly Amenity[] = [
  {
    name: "Swimming pool and sunken lounge",
    description:
      "A pool on the first-floor wellness level with a sunken lounge beside it, shared by every residence. The pools suspended higher in the facade are private to the two penthouses.",
    media: media.poolAndGym,
  },
  {
    name: "Gym",
    description:
      "A fitted gym on the first-floor wellness level, with its own lobby, showers and changing area.",
    media: media.arrivalPodium,
  },
  {
    name: "Sauna",
    description:
      "A timber-lined sauna with tiered benches, off the pool lobby beside the shower and restroom area.",
    media: media.sauna,
  },
  {
    name: "Steam room",
    description:
      "A steam room tiled in blue mosaic with tiered benches, next to the sauna.",
    media: media.steamRoom,
  },
  {
    name: "Yoga and floor exercise studio",
    description:
      "A dedicated studio for yoga and floor work, apart from the main gym floor.",
    media: media.yogaStudio,
  },
  {
    name: "Bar and lounge",
    description:
      "A residents' bar and lounge on the first floor, with its own kitchenette.",
    media: media.residentsLounge,
  },
  {
    name: "Work lounge",
    description:
      "A shared work table along the glazing, for working from the building rather than from the flat.",
    media: media.mediaRoom,
  },
  {
    name: "Conference room",
    description:
      "A conference room on the first floor, with a media and IT room attached.",
    media: media.conferenceRoom,
  },
  {
    name: "Two meeting rooms",
    description:
      "Two further meeting rooms on the same level, one set up for screening as well as for meetings.",
    media: media.meetingRoom,
  },
  {
    name: "Garden and children's play area",
    description:
      "A planted garden at ground level off the lobby lounge, with a children's play area within the gated boundary.",
    media: media.playground,
  },
  {
    name: "Reception and lobby",
    description:
      "A staffed reception and lift lobby at ground level, with a security office and commercial space on the same floor.",
    media: media.reception,
  },
  {
    name: "Lobby lounge",
    description:
      "A lounge off the lobby, glazed on two sides to the garden.",
    media: media.lobbyLounge,
  },
  {
    name: "On-site facilities management",
    description:
      "Facilities management offices, laundry and plant on the first floor, so the building is run from within it.",
  },
  {
    name: "Covered arrival",
    description:
      "A sheltered drop-off beneath the podium, leading directly to the residents' lobby.",
  },
  {
    name: "Gated entrance and security office",
    description:
      "A gated vehicle entrance carrying the Explorer mark in a brass screen, with a security office on the ground floor.",
    media: media.gateDetail,
  },
  {
    name: "Resident parking",
    description:
      "Parking at grade and beneath the podium, within the gated boundary wall.",
  },
  {
    name: "Planted balconies",
    description:
      "Planting integrated into the balcony edges and carried up the full height of the facade.",
  },
  {
    name: "Solar site lighting",
    description: "Solar street lighting to the approach and forecourt.",
  },
];

/**
 * How the building stacks up, taken from the approved section drawing and the
 * mix confirmed by the client.
 *
 * The drawing names its own levels — "3RD FL. (TYPICAL)", "10TH FL. (LOWER
 * PENT)", "11TH FL. (UPPER PENT)" — so the penthouse is a duplex over the top
 * two floors rather than a single storey.
 *
 * Note what is deliberately absent: a total unit count. The typical mix is
 * three apartments per floor, but which of the lower levels are residential is
 * not something to infer from a section, so `projectFacts` keeps the total
 * pending until the developer states it.
 */
export const buildingLevels: readonly {
  name: string;
  detail: string;
  kind: "below" | "podium" | "typical" | "penthouse" | "roof";
}[] = [
  {
    name: "Basement",
    detail: "Structured parking below the podium, within the gated boundary.",
    kind: "below",
  },
  {
    name: "Ground floor",
    detail:
      "Covered arrival and drop-off, the residents' lobby, and parking at grade. Solar lighting to the approach and forecourt.",
    kind: "podium",
  },
  {
    name: "Podium",
    detail:
      "A glazed fitness room above the arrival court, looking back over the forecourt.",
    kind: "podium",
  },
  {
    name: "Typical floors",
    detail:
      "Three apartments to a floor: two three-bedroom residences and one two-bedroom.",
    kind: "typical",
  },
  {
    name: "Levels 10 and 11",
    detail:
      "The six-bedroom penthouse, arranged as a duplex over the lower and upper penthouse floors, with the suspended pool and the private cinema room.",
    kind: "penthouse",
  },
  { name: "Roof", detail: "Plant and the cantilevered roof blade.", kind: "roof" },
];

/** The mix on a typical residential floor, as confirmed by the client. */
export const typicalFloorMix = {
  threeBedroom: 2,
  twoBedroom: 1,
  summary: "Two three-bedroom residences and one two-bedroom, per floor.",
} as const;

/**
 * What is around the site.
 *
 * Every entry here was checked against live map data at the confirmed pin
 * (0.3281903, 32.5870894) rather than written from memory. What is deliberately
 * absent is drive times: Kampala traffic makes any single figure misleading,
 * and spec §2 rules out inventing journey times. Distances are described by
 * relationship — same avenue, walking distance, adjoining district — which is
 * checkable, rather than by a number that is not.
 *
 * This is map data, not a developer claim. The page says so.
 */
export interface NearbyGroup {
  heading: string;
  note?: string;
  places: readonly string[];
}

export const neighbourhood: readonly NearbyGroup[] = [
  {
    heading: "The golf course",
    note:
      "Uganda Golf Club is addressed on Kitante Road at John Babiha (Acacia) Avenue — the same avenue as the tower — and its fairways open immediately south-west of the site.",
    places: ["Uganda Golf Club", "Kololo Independence Park"],
  },
  {
    heading: "Shopping",
    note: "Acacia Mall is the closest, on the same avenue.",
    places: [
      "Acacia Mall",
      "Forest Mall, Naguru",
      "Garden City Shopping Mall",
      "The Oasis Mall",
      "Kingdom Kampala",
    ],
  },
  {
    heading: "Health",
    places: [
      "Nakasero Hospital",
      "Kampala Hospital",
      "Case Medical Centre",
      "Victoria Medical Centre",
      "Mulago National Referral Hospital",
    ],
  },
  {
    heading: "Schools",
    places: [
      "Kitante Hill Secondary School",
      "Nakasero Primary School",
      "City Parents School",
      "Lincoln International School",
      "Sir Apollo Kagwa Primary School, Nakasero",
    ],
  },
  {
    heading: "Eating out",
    places: [
      "Mediterraneo Restaurant",
      "Cantine Divino",
      "Zorba",
      "Stonehaven Restaurant & Winery",
      "Piato Restaurant",
    ],
  },
  {
    heading: "Banking",
    places: [
      "Stanbic Bank, Nakasero",
      "Housing Finance Bank, Nakasero",
      "dfcu Bank, Kyadondo",
      "Ecobank Uganda",
    ],
  },
];

/** How the site connects to the rest of the city. */
export const routes: readonly { name: string; detail: string }[] = [
  {
    name: "John Babiha (Acacia) Avenue",
    detail:
      "The site address. Runs south-west past the golf course toward Kitante and the city centre, and north to Kisementi and Acacia Mall.",
  },
  {
    name: "Kira Road",
    detail: "North-west toward Mulago, the museum and Wandegeya.",
  },
  {
    name: "Yusuf Lule Road",
    detail:
      "The main southern route down to Nakasero and the central business district.",
  },
  {
    name: "Upper and Lower Kololo Terrace Road",
    detail: "East across Kololo toward Naguru and the eastern suburbs.",
  },
];

export const neighbourhoodSource =
  "Compiled from map data at the confirmed site pin. Drive times are not published: they vary too much with traffic to be quoted honestly. The sales team will talk you through the journey you care about.";

export const amenitiesNote =
  "Shown as designed. The full schedule of common facilities is confirmed by the sales team.";

/**
 * The suspended pool belongs to the penthouse, not to the building. It was
 * previously listed here as a shared amenity, which would have told every
 * two- and three-bedroom buyer they had access to something they do not.
 */
export const amenitiesExclusion =
  "The suspended swimming pool and the cinema room are private to the penthouse and are not shared facilities.";

// ---------------------------------------------------------------------------
// Project facts and narrative
// ---------------------------------------------------------------------------

export const projectFacts: readonly ProjectFact[] = [
  { label: "Location", value: approved("Plot 35 John Babiha (Acacia) Avenue, Kololo, Kampala") },
  {
    label: "Residence types",
    value: approved("Two bedroom, three bedroom, and six-bedroom duplex penthouses"),
  },
  /*
   * Counted from the issued drawings: floors two to nine each carry three
   * apartments (sheets A-104 to A-111, each with three living areas of 109.2,
   * 89.6 and 113.2 m²), plus the two penthouses on ten and eleven. The
   * two-and-one split per floor is the client's confirmed mix. This is the
   * number built, not the number still for sale — availability is a
   * separate figure the developer has not released.
   */
  {
    label: "Total residences",
    value: approved("26 — 24 apartments and 2 penthouses"),
  },
  {
    label: "Apartments",
    value: approved("16 three-bedroom and 8 two-bedroom, three to a floor on floors two to nine"),
  },
  {
    label: "Storeys",
    value: approved("Basement, ground floor and eleven upper floors"),
  },
  { label: "Tenure", value: pending("Confirmed in the sale agreement — ask the sales team") },
  { label: "Expected completion", value: pending("To be confirmed") },
];

export const projectSummary = [
  "Explorer Towers is a residential tower on Acacia Avenue, Kampala, designed around a single idea carried from the street to the top floor: a curved balcony that wraps the building and never breaks.",
  "The curve does the work. It widens the living rooms, turns every principal bedroom towards a view, and carries planting up the full height of the facade. Near the top the floor plate opens and the penthouse pool is suspended in the gap.",
  "Residences are two and three bedroom, with a six-bedroom penthouse above them. Each opens along floor-to-ceiling glazing onto a private balcony, with stone, walnut and brass carried through the interiors.",
];

// ---------------------------------------------------------------------------
// Gallery, progress, downloads
// ---------------------------------------------------------------------------

/**
 * Every image on the site, in reading order. Residence galleries share images
 * with the amenity set — the penthouse is shown through the sky-pool renders —
 * so the list is deduplicated by source: an image appears in the gallery once.
 */
export const galleryItems: readonly Media[] = (() => {
  const ordered = [
    media.streetGoldenHour,
    media.cornerDaylight,
    media.frontElevationDusk,
    media.cornerEvening,
    media.sectionCutawayDusk,
    media.arrivalPodium,
    media.skyPoolTerrace,
    media.skyPoolFacade,
    ...residences.flatMap((residence) => residence.gallery),
    // The amenity renders. Without these the gallery showed none of the rooms
    // the Amenities page lists. Exteriors from the newer set are deliberately
    // not added: the site keeps its existing facade treatment.
    media.poolAndGym,
    media.poolTerraceDay,
    media.poolFromGarden,
    media.lobbyLounge,
    media.reception,
    media.residentsLounge,
    media.diningHall,
    media.mediaRoom,
    media.conferenceRoom,
    media.meetingRoom,
    media.sauna,
    media.steamRoom,
    media.yogaStudio,
    media.playground,
    media.gateDetail,
    media.gatedEntrance,
  ];

  const seen = new Set<string>();
  return ordered.filter((item) => {
    if (seen.has(item.src)) return false;
    seen.add(item.src);
    return true;
  });
})();

/**
 * Spec §2: construction photography must stay separate from renders. No site
 * photographs have been handed over, so this list is deliberately empty and
 * the page shows an honest empty state rather than renders in their place.
 */
export const progressUpdates: readonly ProgressUpdate[] = [];

export const downloads: readonly Download[] = [
  {
    title: "Project brochure",
    description: "Full specification, residence layouts and payment information.",
    file: pending("Request the current brochure"),
  },
  {
    title: "Floor plans",
    description:
      "The full dimensioned set: basement, ground, the first-floor wellness level, every typical floor, and both penthouse levels. Room sizes and structural grid in metres.",
    file: approved({
      href: "/documents/explorer-towers-floor-plans.pdf",
      revised: "25 September 2026",
      sizeLabel: "439 KB PDF, 14 sheets",
    }),
  },
  {
    title: "Schedule of areas",
    description: "Net internal area for every residence, with the area basis stated.",
    file: pending("Request the schedule of areas"),
  },
];

/**
 * The questions buyers actually type.
 *
 * Written for search intent as much as for the page: someone looking for this
 * building searches "3 bedroom apartment for sale in Kampala" or "penthouse
 * Kololo", not "what sizes are available". The headings and wording follow
 * those phrasings so the answer on this page is the answer to the question
 * that was asked.
 *
 * Every answer stays inside what the developer has approved. Where a figure is
 * not released — areas, completion, the penthouse price — the answer says so
 * plainly rather than estimating, because a confident wrong number reaches a
 * search engine and an AI assistant exactly as readily as a right one.
 */
export const faqs: readonly FaqSection[] = [
  {
    heading: "Buying in Kampala",
    items: [
      {
        question: "Where can I buy an apartment in Kampala?",
        answer:
          "Explorer Towers is a residential tower on Plot 35 John Babiha (Acacia) Avenue in Kololo, Kampala's central diplomatic and residential neighbourhood. It offers two-bedroom and three-bedroom residences and a six-bedroom penthouse, all for sale directly from the developer, 969 Development Company Limited, with Shoal Group and Gabonn Associates.",
      },
      {
        question: "How much does a three-bedroom apartment cost in Kampala?",
        answer:
          "At Explorer Towers, three-bedroom residences start at USD 400,000 and two-bedroom residences at USD 300,000. Those are starting prices: the figure for a particular residence depends on its floor and aspect, and the developer confirms it in writing. The six-bedroom penthouse is priced on application.",
      },
      {
        question: "Can I buy a two-bedroom apartment in Kampala?",
        answer:
          "Yes. Two-bedroom residences at Explorer Towers start at USD 300,000. Each has an open living, dining and kitchen space along the curved glazing, two en-suite bedrooms, fitted walnut joinery and a private balcony off the principal suite.",
      },
      {
        question: "Is there a luxury penthouse for sale in Kololo?",
        answer:
          "Yes — two of them. Explorer Towers has a mirrored pair of six-bedroom duplex penthouses across its tenth and eleventh floors, on John Babiha (Acacia) Avenue, Kololo. Each has its own swimming pool and pool deck suspended in the facade, a private cinema room and a sunken lounge, belonging to that residence alone. Both are priced on application — contact the sales team.",
      },
      {
        question: "Can foreigners and Ugandans in the diaspora buy here?",
        answer:
          "Yes. Buyers outside Uganda are welcome. Tell us your time zone in the inquiry form and a meeting will be arranged to suit it. Sales documents and payment terms are issued by the developer and confirmed in writing.",
      },
      {
        question: "Can I reserve a residence through this website?",
        answer:
          "No. The website records your interest and passes it to the sales team. A reservation exists only once the developer confirms it in writing under the sales process in force at the time.",
      },
    ],
  },
  {
    heading: "The location",
    items: [
      {
        question: "Where exactly is Explorer Towers?",
        answer:
          "Plot 35 John Babiha (Acacia) Avenue, Kololo, Kampala, Uganda. John Babiha Avenue is the road still widely known as Acacia Avenue. Uganda Golf Club is addressed on Kitante Road at the same avenue, with its fairways immediately south-west of the site, and Kololo Independence Park is nearby.",
      },
      {
        question: "What is Kololo like as a place to live?",
        answer:
          "Kololo is the central Kampala neighbourhood on the hill above the city, long established as its diplomatic and embassy quarter. John Babiha (Acacia) Avenue runs through it. The Location page shows the approved map and the nearby destinations the developer has confirmed.",
      },
    ],
  },
  {
    heading: "The residences",
    items: [
      {
        question: "What sizes and layouts are available?",
        answer:
          "Two-bedroom residences, three-bedroom residences and two six-bedroom duplex penthouses. Every residence opens along floor-to-ceiling curved glazing onto a private balcony. The full dimensioned floor plan set is on the Downloads page, with room sizes in metres for every level. The sale schedule of areas, which states how balconies and terraces are counted, is issued with the brochure.",
      },
      {
        question: "How many apartments and floors are there?",
        answer:
          "Explorer Towers has 26 residences: 24 apartments and 2 penthouses. The apartments are on floors two to nine, three to a floor — two three-bedroom residences and one two-bedroom — which makes 16 three-bedroom and 8 two-bedroom apartments. The two six-bedroom duplex penthouses are on floors ten and eleven. The building is a basement, a ground floor and eleven upper floors.",
      },
      {
        question: "What amenities does the building have?",
        answer:
          "The whole first floor is given over to wellness and work: a swimming pool with a sunken lounge, a gym, a sauna and steam room, a yoga and floor exercise studio, a bar and lounge, a conference room with a media room attached, and two further meeting rooms. At ground level there is a staffed reception and lobby, a garden with a children's play area, and commercial space. Parking is at grade and in the basement within the gated boundary, and facilities management is on site. Each of the two penthouses additionally has its own suspended pool, pool deck and private cinema room.",
      },
      {
        question: "When will Explorer Towers be completed?",
        answer:
          "The completion date has not been released for publication. The Progress page carries dated construction updates as they are issued, and the sales team can give you the current programme.",
      },
      {
        question: "Are the images photographs of the finished building?",
        answer:
          "No. Every image on this site is an architectural render and is labelled as one. Site photography will appear on the Progress page as construction proceeds, kept separate from the renders.",
      },
      {
        question: "Is the furniture included?",
        answer:
          "Furniture and styling shown in the renders are indicative. The delivered specification is set out in the brochure.",
      },
    ],
  },
  {
    heading: "Visiting and next steps",
    items: [
      {
        question: "Can I visit the site?",
        answer:
          "Yes. Site visits are accompanied by a representative. Request one from the Contact page and the team will confirm the time, the access route and what to bring.",
      },
      {
        question: "How quickly will someone reply?",
        answer:
          "Inquiries are assigned to a named person as soon as they arrive and answered within the sales team's published working hours.",
      },
      {
        question: "How do I get the brochure and floor plans?",
        answer:
          "The dimensioned floor plans download directly from the Downloads page. The brochure, which carries the full specification, the sale schedule of areas with its area basis, and payment information, is requested from the same page.",
      },
    ],
  },
];

export const legal = {
  disclaimer:
    "All images on this site are architectural renders prepared for marketing. Dimensions, finishes, furniture and landscaping are indicative and subject to change. Nothing on this site forms part of an offer or contract.",
};
