"""Prepare the developer and marketing logos for the website.

The supplied artwork is the two marks side by side — Shoal Group and 969
Development — on a large white square. They are a pair and are used as a pair:
this script only trims the surrounding white and makes it transparent, so the
relationship, spacing and proportions stay exactly as delivered. Nothing is
recoloured, reordered or separated.

Three colourways were supplied (charcoal, blue, navy). Charcoal is the one the
site uses; the others are kept in `content/brand/` in case the client changes
the approved version.

Bright Properties, the marketing agent, gets the same treatment from its own
supplied file. Both marks keep black or dark elements, so wherever either sits
on a dark ground the page puts it on a light plate rather than recolouring
approved brand artwork.

Gabonn Associates is the third developer party and was supplied separately, so
it is prepared on its own and composited onto the right of the pair. The join
matches the gap already inside the supplied artwork, so the three read as one
lockup rather than as two images pushed together, and a vertical hairline marks
where the supplied pair ends and the added mark begins.

If `gabonn.png` is absent the script simply skips the composite and writes the
supplied pair unchanged, so the site keeps working until the file arrives.

Writes: site/public/media/brand/developers.png
        site/public/media/brand/bright-properties.png
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BRAND_OUT = ROOT / "site" / "public" / "media" / "brand"

# (source, output, margin in source pixels)
JOBS = [
    (
        ROOT / "content" / "brand" / "developers-charcoal.png",
        BRAND_OUT / "developers.png",
        10,
    ),
    (
        ROOT / "content" / "brand" / "bright logo nb.png",
        BRAND_OUT / "bright-properties.png",
        12,
    ),
]


def is_ground(pixel: tuple[int, int, int, int]) -> bool:
    """True for the white square the artwork was delivered on."""
    red, green, blue, alpha = pixel
    return alpha < 8 or (red > 246 and green > 246 and blue > 246)


def prepare(src: Path, out: Path, margin: int) -> None:
    if not src.exists():
        print(f"skipped  {src.name} (not supplied yet)")
        return

    image = Image.open(src).convert("RGBA")
    width, height = image.size
    pixels = image.load()

    left, right, top, bottom = width, -1, height, -1
    for y in range(height):
        for x in range(width):
            if not is_ground(pixels[x, y]):
                left = min(left, x)
                right = max(right, x)
                top = min(top, y)
                bottom = max(bottom, y)

    if right < 0:
        print(f"skipped  {src.name} (looks blank)")
        return

    box = (
        max(left - margin, 0),
        max(top - margin, 0),
        min(right + 1 + margin, width),
        min(bottom + 1 + margin, height),
    )
    cropped = image.crop(box)

    # Drop the white ground to transparency so the mark sits on the site's warm
    # stone rather than on a white patch that would read as a sticker.
    out_px = cropped.load()
    for y in range(cropped.height):
        for x in range(cropped.width):
            if is_ground(out_px[x, y]):
                out_px[x, y] = (0, 0, 0, 0)

    out.parent.mkdir(parents=True, exist_ok=True)
    cropped.save(out, optimize=True)
    print(
        f"logo     {out.name:<24} {cropped.width}x{cropped.height}  "
        f"{out.stat().st_size / 1000:.0f} KB"
    )


GABONN_SRC = ROOT / "content" / "brand" / "gabonn.png"
GENERATED = ROOT / "site" / "src" / "content" / "developer-lockup.generated.ts"

SUPPLIED_PAIR = ["Shoal Group", "969 Development Company Limited"]


def write_manifest(parties: list[str]) -> None:
    """Record who is actually in the artwork.

    The alt text has to describe the image as it exists, so it is generated
    here rather than typed in the content module. Otherwise adding or removing
    a party leaves the page announcing a mark that is not in the picture, which
    a sighted reader would never catch.
    """
    listed = ", ".join(parties[:-1]) + " and " + parties[-1]
    lines = [
        "// Generated by tools/build-developer-lockup.py. Do not edit by hand.",
        "//",
        "// Regenerate after changing anything in content/brand/:",
        "//   python tools/build-developer-lockup.py",
        "",
        f"export const DEVELOPER_PARTIES = {parties!r}".replace("'", '"')
        + " as const;",
        "",
        f'export const DEVELOPER_ALT = "{listed}";',
        "",
    ]
    GENERATED.write_text(chr(10).join(lines), encoding="utf-8")
    print(f"manifest {GENERATED.name:<24} {len(parties)} parties")


def append_gabonn(pair: Path) -> None:
    """Composite Gabonn Associates onto the right of the supplied pair."""
    if not GABONN_SRC.exists():
        write_manifest(list(SUPPLIED_PAIR))
        print(
            f"pending  {GABONN_SRC.relative_to(ROOT)} not supplied; "
            "developers.png left as the supplied pair"
        )
        return

    trimmed = pair.parent / "_gabonn-trimmed.png"
    prepare(GABONN_SRC, trimmed, 10)
    if not trimmed.exists():
        write_manifest(list(SUPPLIED_PAIR))
        return

    left = Image.open(pair).convert("RGBA")
    right = Image.open(trimmed).convert("RGBA")

    # Match heights by cap height rather than by bounding box: Gabonn's roof
    # glyph rises well above its wordmark, so scaling the whole box to match
    # would leave the word looking smaller than the marks beside it.
    target = int(left.height * 0.78)
    scale = target / right.height
    right = right.resize(
        (max(int(right.width * scale), 1), target), Image.LANCZOS
    )

    gap = int(left.height * 0.34)
    rule = max(int(left.height * 0.012), 1)
    width = left.width + gap + rule + gap + right.width
    canvas = Image.new("RGBA", (width, left.height), (0, 0, 0, 0))

    canvas.alpha_composite(left, (0, 0))

    divider = Image.new(
        "RGBA", (rule, int(left.height * 0.62)), (120, 120, 120, 90)
    )
    canvas.alpha_composite(
        divider, (left.width + gap, (left.height - divider.height) // 2)
    )

    canvas.alpha_composite(
        right,
        (left.width + gap + rule + gap, (left.height - right.height) // 2),
    )

    canvas.save(pair, optimize=True)
    trimmed.unlink()
    write_manifest([*SUPPLIED_PAIR, "Gabonn Associates"])
    print(
        f"lockup   {pair.name:<24} {canvas.width}x{canvas.height}  "
        f"{pair.stat().st_size / 1000:.0f} KB  (Shoal + 969 + Gabonn)"
    )


def main() -> None:
    for src, out, margin in JOBS:
        prepare(src, out, margin)
    append_gabonn(BRAND_OUT / "developers.png")


if __name__ == "__main__":
    main()
